package screens;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author caophuc
 */
public class LoginScreen extends Screen {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        setLocationRelativeTo(null);
//        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        body = new javax.swing.JPanel();
        usnPanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        usernameTxf = new javax.swing.JTextField();
        pwPanel = new javax.swing.JPanel();
        passwordLbl = new javax.swing.JLabel();
        passwordTxf = new javax.swing.JPasswordField();
        loginBtnPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 250));
        getContentPane().setLayout(new java.awt.FlowLayout());

        body.setLayout(new java.awt.GridLayout(3, 0));

        usernameLbl.setText("Tên Đăng Nhập");
        usernameLbl.setPreferredSize(new java.awt.Dimension(100, 30));
        usnPanel.add(usernameLbl);

        usernameTxf.setPreferredSize(new java.awt.Dimension(200, 30));
        usnPanel.add(usernameTxf);

        body.add(usnPanel);

        passwordLbl.setText("Mật Khẩu");
        passwordLbl.setPreferredSize(new java.awt.Dimension(100, 30));
        pwPanel.add(passwordLbl);

        passwordTxf.setPreferredSize(new java.awt.Dimension(200, 30));
        pwPanel.add(passwordTxf);

        body.add(pwPanel);

        loginBtn.setForeground(new java.awt.Color(255, 51, 51));
        loginBtn.setText("Đăng Nhập");
        loginBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtnPanel.add(loginBtn);

        body.add(loginBtnPanel);

        getContentPane().add(body);

        pack();
    }// </editor-fold>
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String username = usernameTxf.getText();
        if (username.equals("giaovu")) {
            changeScreen(new TCHomeScreen());
        } else {
            changeScreen(new SVHomeScreen());
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel body;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginBtnPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxf;
    private javax.swing.JPanel pwPanel;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxf;
    private javax.swing.JPanel usnPanel;
    // End of variables declaration
}
